/**
 * Countries supported
 */

export const COUNTRIES = [
  { code: "ES", name: "España" },
  { code: "DE", name: "Alemania" },
  { code: "DZ", name: "Argelia" },
  { code: "AT", name: "Austria" },
  { code: "BE", name: "Bélgica" },
  { code: "BG", name: "Bulgaria" },
  { code: "CM", name: "Camerún" },
  { code: "CY", name: "Chipre" },
  { code: "HR", name: "Croacia" },
  { code: "DK", name: "Dinamarca" },
  { code: "SK", name: "Eslovaquia" },
  { code: "SI", name: "Eslovenia" },
  { code: "EE", name: "Estonia" },
  { code: "FI", name: "Finlandia" },
  { code: "FR", name: "Francia" },
  { code: "GM", name: "Gambia" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Grecia" },
  { code: "GN", name: "Guinea" },
  { code: "GQ", name: "Guinea Ecuatorial" },
  { code: "HU", name: "Hungría" },
  { code: "IE", name: "Irlanda" },
  { code: "IT", name: "Italia" },
  { code: "LV", name: "Letonia" },
  { code: "LT", name: "Lituania" },
  { code: "LU", name: "Luxemburgo" },
  { code: "ML", name: "Mali" },
  { code: "MT", name: "Malta" },
  { code: "MA", name: "Marruecos" },
  { code: "MR", name: "Mauritania" },
  { code: "NG", name: "Nigeria" },
  { code: "NO", name: "Noruega" },
  { code: "NL", name: "Países Bajos" },
  { code: "PL", name: "Polonia" },
  { code: "PT", name: "Portugal" },
  { code: "GB", name: "Reino Unido" },
  { code: "CZ", name: "República Checa" },
  { code: "RO", name: "Rumanía" },
  { code: "SN", name: "Senegal" },
  { code: "SE", name: "Suecia" },
  { code: "CH", name: "Suiza" },
  { code: "TN", name: "Túnez" },
] as const;

export const DEFAULT_COUNTRY = "ES";
